services:
  bot:
    build: .
    container_name: rag_bot
    env_file:
      - .env
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - ragnet

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
      - ./qdrant_config:/qdrant/config
    restart: unless-stopped
    networks:
      - ragnet

networks:
  ragnet:
    driver: bridge
