version: '3.8'

services:
  bot:
    build: .
    container_name: rag_bot
    env_file:
      - .env
    depends_on:
      - qdrant
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
      - ./qdrant_config/production.yaml:/qdrant/config/production.yaml
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
